### ISSUE TITLE
Measure Antenna Noise Temperature

### ISSUE THREAD

**Issue by ppapadeas** [librespacefoundation/upsat-comms-hardware#4]
in dBK

**Comment by manostheodoridis** [comment]
When talking about Antenna Noise Temperature parameter expressed in dBK it is most likely that we refer to Antenna gain-to-noise-temperature which is a figure of merit (G/T) in the characterization of system performance, where G is the antenna Gain in decibels at the receive frequency and T is the total system temperature of the system (noise from both the antenna and the receiver). 

In our case with an antenna gain of approximately 2.2 dBi we have a figure of merit of around -25 dB/K

**Comment by manostheodoridis** [comment]
Antenna temperature.

Parameter that describes how much noise the antenna produces/sees. 
(In some articles this parameter is also described as the temperature of a hypothetical resistor at the input of an ideal receiver (noise-free) that would generate the same output noise power per unit bandwidth as that as the antenna output at a particular frequency.) 

Not the physical temp of the antenna. 
In various docs it is said that Antenna temperature is also sometimes referred to as Antenna Noise Temperature or Antenna Sky Temperature (IARU/AMSAT). 
Depends on its radiation pattern. 
Depends on the environment. 
  
In order to define this parameter in detail we need:
The temperature distribution T(θ,φ) 
The radiation pattern  R(θ,φ) 
To finally solve this  

So basically the antenna noise temperature would vary depending on its main/side lobes and where they are pointing (sun, earth, space)  and the contribution of each noise source depends on the power of the source and the size of the antenna lobes. 

Sources of antenna noise temperature:
Galactic radiation
Earth heating
The sun
Electrical devices
The antenna itself 

Typically, simpler mathematical estimates are used (AMSAT-IARU). For a small satellite in LEO the two main factors that contribute to the antenna noise temperature are:
the sky itself (nominally 2.7 K but for frequencies bellow 2GHz also includes galactic noise varying  from 80K to 1700K )
the average Earth temperature that varies with location, time and man-made noise sources but has an average value of 290K

At VHF frequencies (and to a lesser extent at UHF) galactic noise can be observed even with small antennas. The sky brightness is highest in directions that intercept the disk or plane of the Milky Way. At 146 MHz this value can vary from 80K to 1700K
“Radio Propagation in Satellite Communication,” Van Norstrand Reinold.

So one scenario (not the only one of course) would be to assume that the UPSat's antenna field of view 60% includes the Earth  (290K) and 40% the sky (value between 80K-1700K lets assume 890K)    

so the antenna or sky temperature (or antenna noise temperature) would approximately be:
T= 0,6*290+0,4*890= 174+365= 530K. 

But again when someone is referring to the antenna noise temp in dBK i assume that the reference might be for the G/T (Antenna gain-to-noise-temperature in dB/K)
